# Generated by Django 4.1.2 on 2022-10-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cnab',
            unique_together={('tipo', 'data', 'valor', 'cpf', 'cartao', 'hora', 'dono_loja', 'nome_loja')},
        ),
    ]
