# Generated by Django 4.1.2 on 2022-10-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cnab_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField()),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('natureza', models.CharField(max_length=10)),
                ('sinal', models.CharField(max_length=1)),
            ],
        ),
    ]
