# Generated by Django 4.1.2 on 2022-10-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnab',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transacao'),
        ),
    ]
